export const CREATE_TEMPLATE = "CREATE_TEMPLATE";
export const CREATE_RECORDS = "CREATE_RECORDS";
export const UPDATE_RECORDS = "UPDATE_RECORDS";
export const DELETE_RECORDS = "DELETE_RECORDS";
export const UPDATE_TEMPLATE = "UPDATE_TEMPLATE";


